version: '2'

services:

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_DATABASE: "users"
        MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d

  myapp:
    build: .
    ports:
      - 80:8080
    links:
        - db
