version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Hao1995/docker-example
    # working_directory: /docker-example
    docker:
      # specify the version
      - image: circleci/golang:1.8
      
    
    steps:
      - checkout
      - setup_remote_docker
      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          name: Run tests
          command: |
            docker-compose up -d
      - deploy:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker tag dockerexample_myapp $DOCKER_HUB_USER_ID/docker-example:$CIRCLE_SHA1
            docker tag dockerexample_myapp $DOCKER_HUB_USER_ID/docker-example:latest
            docker push $DOCKER_HUB_USER_ID/docker-example:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/docker-example:latest